### PR TITLE
big update. please check twice.

### LINKED ISSUE #3: Strange behavior when loaded twice
Say you have project A, which has a require('longjohn') line in it,
and you also have a project B which is unit tests for A and some other things, and also requires longjohn.  The two do not interact well (see stack trace below).

Workarounds:
 - Comment out one or the other's use of longjohn
 - Make one's node_modules/longjohn a symlink to the other's

but neither will work in the case that it's a dependency of a third-party dependency.

Error: TypeError: Cannot call method 'emit' of null
TypeError: Cannot call method 'emit' of null
    at Socket.onServerResponseClose (http.js:906:21)
    at Socket.new_callback (/home/tim/work/abcd/incubator/xyzserver/node_modules/longjohn/index.js:107:16)
    at Socket.EventEmitter.emit (events.js:115:20)
    at Socket.vows.describe.options.Emitter.emit [as emit] (/home/tim/work/chiliad/incubator/tests/node_modules/vows/lib/vows.js:237:24)
    at Socket._destroy.destroyed (net.js:358:10)
    at new_callback (/home/tim/work/abcd/incubator/xyzserver/node_modules/longjohn/index.js:107:16)
    at process.startup.processNextTick.process._tickCallback [as _tickCallback] (node.js:315:13)
    at process.startup.processMakeCallback.process._makeCallback [as _makeCallback] (node.js:243:15)
---------------------------------------------
    at ServerResponse.ServerResponse.assignSocket [as assignSocket] (http.js:912:10)
    at HTTPParser.parser.onIncoming (http.js:1748:11)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
    at Socket.socket.ondata (http.js:1682:22)
    at TCP.onread (net.js:404:27)
    at process.startup.processMakeCallback.process._makeCallback [as _makeCallback] (node.js:238:20)

### LINKED ISSUE #15: No limit on serialization of error
Every so often, we'll run into an error that longjohn tries to serialize, and in attempting to do so will peg the CPU and gobble up RAM (like 1+GB).

It seems like it attempts to serialize our entire application in a single Object graph...

```js
uncaughtException: { [Error: Invalid timestamp. Please provide timezone as fallback]
  __cached_trace__: 
   [ { receiver: 
        { localTime: [Function],
          humanizeDuration: [Function] },
       fun: [Function],
       pos: 401 },
     { receiver: undefined,
       fun: [Function: grouper],
       pos: 4432 },
     { receiver: 
        { ArrayBuffer: [Function: ArrayBuffer],
          Int8Array: { [Function: Int8Array] BYTES_PER_ELEMENT: 1 },
          Uint8Array: { [Function: Uint8Array] BYTES_PER_ELEMENT: 1 },
          Uint8ClampedArray: { [Function: Uint8ClampedArray] BYTES_PER_ELEMENT: 1 },
          Int16Array: { [Function: Int16Array] BYTES_PER_ELEMENT: 2 },
          Uint16Array: { [Function: Uint16Array] BYTES_PER_ELEMENT: 2 },
          Int32Array: { [Function: Int32Array] BYTES_PER_ELEMENT: 4 },
          Uint32Array: { [Function: Uint32Array] BYTES_PER_ELEMENT: 4 },
          Float32Array: { [Function: Float32Array] BYTES_PER_ELEMENT: 4 },
          Float64Array: { [Function: Float64Array] BYTES_PER_ELEMENT: 8 },
          DataView: [Function: DataView],
          global: [Circular],
          process: 
           { title: 'node',
             version: 'v0.8.21',
             moduleLoadList: 
              [ 'Binding evals',
                'Binding natives',
                'NativeModule events',
                'NativeModule buffer',
                'Binding buffer',
                'NativeModule assert',
                // several thousands of additional lines omitted ...
```

It might be worth using util's `inspect` to mitigate this.

### LINKED ISSUE #32: Original removeListener is not executed
In this code:

```
var longjohn = require('longjohn');
var EventEmitter = require('events').EventEmitter;

var ee = new EventEmitter();

ee.on('removeListener', function(event, listener) {
    console.log('removeListener: ' + event);
});

ee.on('data', function() {
});

ee.removeAllListeners('data');
```
The *removeListener* is never executed, while without *longjohn* it is. Is it expected or a bug?

Thanks!

### LINKED ISSUE #46: Huge CPU usage
I have used Node.js (0.10.33) quite long time with 'longjohn' in the clustered application. No any bad affect of 'longjohn' was detected there. The application worked stable and used about 20% of CPU time.
Recently I have updated my Nodejs engine up to latest version (0.12.5) and correspondingly did update for all dependencies. The 'longjonh' was updated to 0.2.7 version. But, unfortunately, after restart my application began to eat up to 95-100% of CPU time. The commenting of 'var longjohn = require('longjohn');' fixed the situation and now it's using no more than 20% of CPU time.
Can you please explain what is happening? Is it my fault? Or there is some bug?

### PR DESCRIPTION
**Pull request by drauggres**
fix #3 
fix #15
fix #32 
fix #46

Also, looks like #33 fixed too.

### CODE REVIEW

**Comment by drauggres** [comment]
@timboudreau @derjust @santigimeno @boutell
@mattinsler

**Comment by mattinsler** [comment]
Published as version **0.2.8**. Thanks so much for all the fixes!!!

**Comment by yinrong** [comment]
Hi, there is still a problem!

```
url='xxx'
//require('longjohn')
require('request')
.get(url)
.pipe(require('zlib').createGunzip())
.pipe(require('fs').createWriteStream('t0.gz'))
```

uncomment "longjohn" will lead to the following error:

```
node_modules/longjohn/dist/longjohn.js:194
        throw e;
        ^

Error: socket hang up
    at onHangUp (_tls_wrap.js:1076:19)
    at g (events.js:260:16)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
---------------------------------------------
    at Readable.on (_stream_readable.js:665:33)
    at tickOnSocket (_http_client.js:486:10)
    at onSocketNT (_http_client.js:502:5)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
---------------------------------------------
    at ClientRequest.onSocket (_http_client.js:494:11)
    at Agent.addRequest (_http_agent.js:143:9)
    at new ClientRequest (_http_client.js:139:16)
    at exports.request (http.js:31:10)
    at exports.request (https.js:173:15)
...
---------------------------------------------
...
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Module._load (module.js:311:12)
```

the header of the url I'm getting is:
```
HTTP/1.1 200 OK
Content-Disposition: attachment; filename=keyword-20151113-165926-b6851a54e9f74fe1da0869140820af82.gz
Content-Type: application/octet-streamn
Date: Fri, 13 Nov 2015 09:30:19 GMT
Server: Apache
Last-Modified: Fri, 13 Nov 2015 09:00:24 GMT
ETag: "8000000063891557-37e319-524684a38fa00"
Accept-Ranges: bytes
Content-Type: application/x-gzip
Content-Length: 3662617
```

**Comment by drauggres** [comment]
Take a look at #52 and #53, @yinrong.

**Pull request merged**
